apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "volsync.fullname" . }}
  labels:
    control-plane: {{ include "volsync.fullname" . }}-controller
    {{- include "volsync.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.hubconfig.replicaCount }}
  selector:
    matchLabels:
      control-plane: {{ include "volsync.fullname" . }}-controller
      {{- include "volsync.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        control-plane: {{ include "volsync.fullname" . }}-controller
        ocm-antiaffinity-selector: "volsync"
        {{- include "volsync.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.global.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.pullSecret }}
      {{- end }}
      serviceAccountName: {{ include "volsync.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: kube-rbac-proxy
          args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10
            {{- if .Values.metrics.disableAuth }}
            - --ignore-paths=/metrics
            {{- end }}
          image: {{ .Values.global.imageOverrides.kube_rbac_proxy }}
          ports:
            - containerPort: 8443
              name: https
        - name: manager
          args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
            - --rclone-container-image={{ .Values.global.imageOverrides.volsync_mover_rclone }}
            - --restic-container-image={{ .Values.global.imageOverrides.volsync_mover_restic }}
            - --rsync-container-image={{ .Values.global.imageOverrides.volsync_mover_rsync }}
            - --scc-name={{ include "volsync.fullname" . }}-mover
          command:
            - /manager
          image: {{ .Values.global.imageOverrides.volsync }}
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      {{- with .Values.hubconfig.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      tolerations:
        - key: dedicated
          operator: Exists
          effect: NoSchedule
        - effect: NoSchedule 
          key: node-role.kubernetes.io/infra 
          operator: Exists
